{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "optimacs.ui.fullname" . }}
  labels:
    {{- include "optimacs.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "optimacs.ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ui.service.port }}
      targetPort: http
{{- end }}
